import Foundation

enum CogQuizContent {
    static let all: [CogQuizQuestion] = [
        CogQuizQuestion(id: "q01",
            prompt: "Two meshed gears always turn…",
            options: ["In the same direction", "In opposite directions", "At the same speed", "Only clockwise"],
            correct: 1,
            explanation: "Meshed teeth move together at the rim, so the wheels must rotate opposite ways — add an idler to keep direction."),
        CogQuizQuestion(id: "q02",
            prompt: "A 24-tooth gear drives a 12-tooth gear. The small gear…",
            options: ["Turns twice as fast", "Turns half as fast", "Turns at the same speed", "Stops"],
            correct: 0,
            explanation: "The small gear must swallow the same number of teeth per second, so with half the teeth it turns twice as fast."),
        CogQuizQuestion(id: "q03",
            prompt: "What hides inside a zipper's slider?",
            options: ["A tiny spring", "A Y-shaped wedge", "A magnet", "A miniature gear"],
            correct: 1,
            explanation: "The slider's hidden wedge angles each tooth into its neighbour — closing or prying them apart one at a time."),
        CogQuizQuestion(id: "q04",
            prompt: "In a pin tumbler lock, the plug can rotate only when…",
            options: ["All springs are removed", "Every pin split sits exactly on the shear line", "The key is turned upside down", "The driver pins fall out"],
            correct: 1,
            explanation: "The right key lifts every stack so the cut between key pin and driver pin lands exactly on the plug-housing boundary."),
        CogQuizQuestion(id: "q05",
            prompt: "The click of a retractable pen comes from…",
            options: ["The spring snapping", "Ink pressure", "A rotating cam dropping into a slot", "The tip hitting the barrel"],
            correct: 2,
            explanation: "Each press twists a toothed cam half a step; the click is the cam snapping into its next resting slot."),
        CogQuizQuestion(id: "q06",
            prompt: "In a music box, longer comb teeth play…",
            options: ["Higher notes", "Lower notes", "Louder notes", "No notes"],
            correct: 1,
            explanation: "Longer teeth vibrate more slowly, giving lower pitches — the comb is a tuned metal keyboard."),
        CogQuizQuestion(id: "q07",
            prompt: "The spinning fan in a music box is there to…",
            options: ["Cool the spring", "Make a whirring sound", "Keep the tempo steady with air resistance", "Polish the cylinder"],
            correct: 2,
            explanation: "The governor fan is an air brake: it loads the gear train so the tune plays at an even speed as the spring unwinds."),
        CogQuizQuestion(id: "q08",
            prompt: "A worm gear pairing a 1-start worm with a 40-tooth wheel gives a ratio of…",
            options: ["4:1", "40:1", "1:40 speeding up", "2:1"],
            correct: 1,
            explanation: "Each worm revolution advances the wheel exactly one tooth, so 40 turns of the worm make one turn of the wheel."),
        CogQuizQuestion(id: "q09",
            prompt: "Why do guitar tuning pegs hold their setting?",
            options: ["String tension is too weak to matter", "The worm drive self-locks", "They're glued", "A ratchet clicks inside"],
            correct: 1,
            explanation: "A worm wheel usually can't drive its worm backwards — friction in the thread wins, so the string can't unwind the peg."),
        CogQuizQuestion(id: "q10",
            prompt: "Rack and pinion converts…",
            options: ["Rotation into straight-line motion", "Heat into motion", "Speed into sound", "Rotation into faster rotation"],
            correct: 0,
            explanation: "The pinion's teeth walk along the straight rack, moving it a fixed distance per degree of turn — that's why steering feels precise."),
        CogQuizQuestion(id: "q11",
            prompt: "In the planetary gearset shown in this app, which member is held fixed?",
            options: ["The sun gear", "The planet gears", "The ring gear", "The carrier"],
            correct: 2,
            explanation: "With the ring fixed, driving the sun makes the carrier turn slowly the same way — the classic reduction setup."),
        CogQuizQuestion(id: "q12",
            prompt: "Planetary gearsets are unusually strong because…",
            options: ["They use special steel", "Load is shared across several planets at once", "They spin slowly", "The ring absorbs shocks"],
            correct: 1,
            explanation: "Three or more planets mesh at the same time, splitting the load across multiple teeth — compact yet mighty."),
        CogQuizQuestion(id: "q13",
            prompt: "A crank and slider converts…",
            options: ["Rotation into back-and-forth motion", "Force into heat", "Speed into torque", "Nothing — it's decorative"],
            correct: 0,
            explanation: "The offset crank pin drags the rod, which drives the slider along its line — and it works in reverse as an engine."),
        CogQuizQuestion(id: "q14",
            prompt: "The 'dead centres' of a crank mechanism are…",
            options: ["Worn-out bearings", "Stroke ends where no turning force passes", "The middle of the stroke", "Broken teeth"],
            correct: 1,
            explanation: "When crank and rod line up at each stroke end, pushing the slider gives no rotation — flywheels coast engines through."),
        CogQuizQuestion(id: "q15",
            prompt: "A cam's egg-shaped outline is really…",
            options: ["A manufacturing accident", "A graph of lift against time wrapped around a shaft", "A way to save metal", "Pure decoration"],
            correct: 1,
            explanation: "Distance from centre to edge at each angle equals follower height at that instant — motion designed in advance."),
        CogQuizQuestion(id: "q16",
            prompt: "The spring on a cam follower exists to…",
            options: ["Speed up the cam", "Keep the follower pressed onto the profile", "Absorb heat", "Make noise"],
            correct: 1,
            explanation: "Without it, at speed the follower would fly off the lobe and chatter back down — contact must never be lost."),
        CogQuizQuestion(id: "q17",
            prompt: "Ratchet teeth are shaped with…",
            options: ["Two steep faces", "Two gentle slopes", "One gentle slope and one steep face", "No slopes at all"],
            correct: 2,
            explanation: "The pawl slides up the gentle slope and drops off the steep face — geometry that permits one direction and forbids the other."),
        CogQuizQuestion(id: "q18",
            prompt: "The clicking when you pedal a bicycle backwards is…",
            options: ["The chain complaining", "A freewheel ratchet's pawls skipping over teeth", "Loose spokes", "The brake rubbing"],
            correct: 1,
            explanation: "Inside the rear hub a ratchet lets the wheel overrun the pedals; its spring-loaded pawls click over the teeth."),
        CogQuizQuestion(id: "q19",
            prompt: "In a wiper linkage, the motor crank…",
            options: ["Swings back and forth", "Spins continuously in one direction", "Reverses every wipe", "Moves the glass"],
            correct: 1,
            explanation: "The four-bar geometry converts the crank's steady circles into the rocker's to-and-fro sweep — the motor never reverses."),
        CogQuizQuestion(id: "q20",
            prompt: "Both wiper blades stay in step because…",
            options: ["Two motors are synchronised", "A parallel link ties the rocker arms together", "They're magnetic", "The driver adjusts them"],
            correct: 1,
            explanation: "A connecting link joins the two rockers into a parallelogram, so both arms copy the same swing exactly."),
        CogQuizQuestion(id: "q21",
            prompt: "A clock's tick and tock are the sounds of…",
            options: ["The pendulum hitting its case", "The two anchor pallets landing on the escape wheel", "Gears meshing", "The spring unwinding"],
            correct: 1,
            explanation: "Each half-swing one pallet stops the wheel with a tiny slam — two beats per full pendulum swing."),
        CogQuizQuestion(id: "q22",
            prompt: "What single property sets a pendulum's beat?",
            options: ["Its weight", "Its length", "How hard you push it", "The metal it's made of"],
            correct: 1,
            explanation: "Galileo's insight: swing wide or narrow, heavy or light — only the pendulum's length sets its period."),
        CogQuizQuestion(id: "q23",
            prompt: "Why doesn't a clock's pendulum ever stop?",
            options: ["It's frictionless", "Each escaping tooth feeds it a tiny push", "It's magnetic", "It actually stops nightly"],
            correct: 1,
            explanation: "The escapement returns a whisper of the drive weight's energy to the pendulum at every beat — replacing losses."),
        CogQuizQuestion(id: "q24",
            prompt: "The four strokes of a petrol engine, in order, are…",
            options: ["Bang, blow, suck, squeeze", "Suck, squeeze, bang, blow", "Squeeze, suck, blow, bang", "Suck, bang, squeeze, blow"],
            correct: 1,
            explanation: "Intake, compression, power, exhaust — mechanics remember it as 'suck, squeeze, bang, blow'."),
        CogQuizQuestion(id: "q25",
            prompt: "How many crank revolutions does one full four-stroke cycle take?",
            options: ["One", "Two", "Four", "Half"],
            correct: 1,
            explanation: "Each stroke is half a revolution; four strokes make two full turns of the crankshaft per single power stroke."),
        CogQuizQuestion(id: "q26",
            prompt: "The flywheel's job in an engine is to…",
            options: ["Cool the cylinder", "Store spin to coast through the three unpowered strokes", "Filter the fuel", "Open the valves"],
            correct: 1,
            explanation: "Only one stroke in four delivers power; the heavy flywheel's stored momentum smooths out the rest."),
        CogQuizQuestion(id: "q27",
            prompt: "Locomotive side rods exist to…",
            options: ["Decorate the wheels", "Couple all driving wheels so they push together", "Brake the train", "Hold the boiler up"],
            correct: 1,
            explanation: "Linking every driver's crank pin makes the wheels grip the rail as a team — more traction, no slipping."),
        CogQuizQuestion(id: "q28",
            prompt: "Why are a locomotive's two cylinder cranks set 90° apart?",
            options: ["It looks better", "So one is always mid-push when the other is at a dead centre", "To save steel", "To reduce noise"],
            correct: 1,
            explanation: "Quartering guarantees the engine can always start and pull smoothly — one cylinder covers the other's dead spot."),
        CogQuizQuestion(id: "q29",
            prompt: "In a block and tackle, your force multiplier equals…",
            options: ["The number of pulleys", "The number of rope strands holding the moving block", "The rope's thickness", "The weight of the blocks"],
            correct: 1,
            explanation: "Each strand supporting the lower block carries a share of the load — count the strands, know your advantage."),
        CogQuizQuestion(id: "q30",
            prompt: "Lifting a crate 1 m with a two-strand tackle means pulling…",
            options: ["1 m of rope", "2 m of rope", "Half a metre", "No rope at all"],
            correct: 1,
            explanation: "Half the force, twice the distance — energy in equals energy out, always."),
        CogQuizQuestion(id: "q31",
            prompt: "An idler gear between two gears changes…",
            options: ["The ratio", "The direction of the output only", "The speed only", "Nothing at all"],
            correct: 1,
            explanation: "The idler flips rotation back to matching directions but drops out of the ratio arithmetic entirely."),
        CogQuizQuestion(id: "q32",
            prompt: "Oil in a machine bearing works by…",
            options: ["Making surfaces sticky", "Keeping metal surfaces apart on a thin film", "Cooling only", "Filling scratches"],
            correct: 1,
            explanation: "A healthy bearing floats its shaft on an oil film thinner than a hair — the metals never actually touch."),
    ]
}
